[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22.16.0"
  NPM_FLAGS = "--version"

[functions]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs"
